ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = 1
warningCode = 1

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unreachable-code]
[rule.get-return]
[rule.early-return]
[rule.identical-branches]
[rule.defer]
    arguments=[["loop","method-call","return"]]
[rule.string-of-int]
[rule.waitgroup-by-value]
[rule.range-val-address]
[rule.argument-limit]
    arguments=[10]
[rule.atomic]
[rule.bool-literal-in-expr]
[rule.deep-exit]
[rule.function-result-limit]
  arguments=[5]
[rule.modifies-value-receiver]
[rule.modifies-parameter]
[rule.unnecessary-stmt]
[rule.cyclomatic]
  arguments = [9]
[rule.cognitive-complexity]
    Arguments = [10]
